### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-python#105]
* [x] Update `setup.py`: include README, update URL, add other URLs #106 & #104
* [x] Documentation #104 
* [x] mention scripts in docs #116
* [x] Add release workflow #112
* [x] ~~Fix installing wheels in CI on Windows~~ not going to install & test wheels for windows on release workflows.
* [x] Add MANIFEST.in for sdists #113 
* [x] Mention analogy + similarity scripts in README #114 

I think the other issues can be resolved in 0.7.1 (e.g. error handlers for bad utf8 or batched lookups).

Is there anything else that you think should be done before the release?

**Comment by danieldk** [comment]
I agree that these things can wait until a later version.

**Comment by sebpuetz** [comment]
I don't think there's anything as frustrating as poking around in CI configs. I gave up on verifying the Windows wheels on CI, I tested it locally on my Windows system and I can install wheels and tests pass.

I pushed the `release-0.7.0` branch with the bumped version number, changed links for documentation and added the `0.7.0` tag.

We only need to add the pypi username & password and publish the release, that should put the wheels on pypi.

**Comment by danieldk** [comment]
Nice!!! CI poking is indeed frustrating, especially Windows & macOS, since you can't emulate them with Docker. At least you have a Windows system to test ;).

I'll update the derivation in our Nix repo and make it replace the old Rust version.

Thanks for doing all the work! This is shaping up to be a nice release and provides a much nicer API than the old module.

**Comment by sebpuetz** [comment]
Meh, I pushed out the release earlier but it turns out that the manylinux wheels are broken because the manylinux container doesn't define `htole32` and `htole64` in `endian.h`.  Guess that's what I get for not properly doing test runs. I hacked something together that passes CI and works with the manylinux docker by adding a self-defined macro to `portable_endian.h` which is set through a environment variable...

**Comment by sebpuetz** [comment]
Closing this since we released the wheel: https://github.com/finalfusion/finalfusion-python/releases/tag/0.7.1 & https://pypi.org/project/finalfusion/0.7.1/
